### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "practice",
  "email": "prac@test.com",
  "password": "password",
  "password_confirmation": "password",
  "admin": false
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "shane@test.com",
  "password": "password"
}

### Users Index
GET http://localhost:3000/users.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgxNDQxMTR9.98wKgVTM9wLxF5teeR13LfHT2a8xB8ZOjybD-MNv-LI
