### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "practice",
  "email": "prac@test.com",
  "password": "password",
  "password_confirmation": "password",
  "admin": false
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "shane@test.com",
  "password": "password"
}

### Users Index
GET http://localhost:3000/users.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgxNDQxMTR9.98wKgVTM9wLxF5teeR13LfHT2a8xB8ZOjybD-MNv-LI



# Friends HTTP Tests



### Friends Index
GET http://localhost:3000/friends.json
Content-Type: application/json

### Friends Show
GET http://localhost:3000/friends/1.json
Content-Type: application/json

### Friends Create
POST http://localhost:3000/friends.json
Content-Type: application/json

{
  "name": "Alex",
  "details": "Tall, loveable, and sassy. Way too good at video games.",
  "points": 0,
  "image_url": ""
}

### Friend Update
PATCH http://localhost:3000/friends/1.json
Content-Type: application/json

{
  "name": "Alex",
  "details": "Tall, loveable, and sassy. Way too good at video games.",
  "points": 0,
  "image_url": "Gobblydegook"
}

### Friend Delete
DELETE http://localhost:3000/friends/1.json
Content-Type: application/json



# Good Deeds Routes

### good_deeds Index
GET http://localhost:3000/good_deeds.json
Content-Type: application/json

### good_deeds Show
GET http://localhost:3000/good_deeds/1.json
Content-Type: application/json

### good_deeds Create
POST http://localhost:3000/good_deeds.json
Content-Type: application/json

{
  "title": "Gave me a cookie",
  "description": "was choclate and peanut butter",
  "value": 1400,
  "friend_id": 2,
  "image_url": ""
}

### good_deeds Update
PATCH http://localhost:3000/good_deeds/1.json
Content-Type: application/json

{
  "title": "Gave me a cookie",
  "description": "was choclate and peanut butter",
  "value": 1400,
  "friend_id": 2,
  "image_url": "bb"
}

### good_deeds delete
DELETE http://localhost:3000/good_deeds/1.json
Content-Type: application/json